In [12]:
import pandas as pd
import numpy as np
from agent_based_model import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [29]:
infected_init_dic = {'H1N1': 20, 'H3N2': 0, 'B': 0}
# alpha -- 78% susceptible
alpha_dic = {'H1N1': 0.78, 'H3N2': 0.74, 'B': 0.6} # H1N1 was 0.78
lmbd = 0.3 # was 0.3
num_runs = 1

strains_keys = ['H1N1', 'H3N2', 'B']

# in data folder schould be 3 files: 'people.txt', 'households.txt', 'schools.json'
data_folder = 'samara_about_370k/'

data_path = 'samara_about_370k/'
results_dir = 'samara_about_370k_res1/'

if not os.path.exists(results_dir):
    os.makedirs(results_dir)
    print("Directory created successfully!")
else:
    print("Directory already exists!")
# sys.exit()

data, households, dict_school_id = load_data(data_path)
data, households, dict_school_id = preprocess_data(
    data, households, dict_school_id)
dict_school_len = [len(dict_school_id[i])
                   for i in dict_school_id.keys()]
data = set_initial_values(data, strains_keys, alpha_dic)

Directory already exists!

In [30]:
days = range(1, 10)
results_dic, number_seed, lmbd, SEIRb_day = main_function(
                0, data_folder=data_folder, dataset=data,
              dict_school_id_all=dict_school_id, lmbd=lmbd, 
              infected_init_dic=infected_init_dic,
              days=days, dict_school_len=dict_school_len)

100%|██████████| 3/3 [00:00<00:00, 34.88it/s]

All inf:  20
day 1, H1N1: new I 20 (all I 20, all S 287688), beta: 0.00000348
day 1, H3N2: new I 0 (all I 0, all S 274191), beta: nan
day 1, B: new I 0 (all I 0, all S 222317), beta: nan

Proc MainProcess, Day 1, time elapsed: 0.8471623000000363 sec
All inf:  1325
day 2, H1N1: new I 0 (all I 20, all S 286968), beta: 0.00000000
day 2, H3N2: new I 0 (all I 0, all S 274191), beta: nan
day 2, B: new I 0 (all I 0, all S 222317), beta: nan

Proc MainProcess, Day 2, time elapsed: 0.8347627999996803 sec
All inf:  2045
day 3, H1N1: new I 1305 (all I 1325, all S 284319), beta: 0.00000346
day 3, H3N2: new I 0 (all I 0, all S 274191), beta: nan
day 3, B: new I 0 (all I 0, all S 222317), beta: nan

Proc MainProcess, Day 3, time elapsed: 1.0045113999999558 sec
All inf:  4694
day 4, H1N1: new I 720 (all I 2045, all S 284319), beta: 0.00000124
day 4, H3N2: new I 0 (all I 0, all S 274191), beta: nan
day 4, B: new I 0 (all I 0, all S 222317), beta: nan

Proc MainProcess, Day 4, time elapsed: 0.37377239999977974 sec
All inf:  4694
day 5, H1N1: new I 2649 (all I 4694, all S 284319), beta: 0.00000198
day 5, H3N2: new I 0 (all I 0, all S 274191), beta: nan
day 5, B: new I 0 (all I 0, all S 222317), beta: nan

Proc MainProcess, Day 5, time elapsed: 0.41493039999977555 sec
All inf:  4694
day 6, H1N1: new I 0 (all I 4694, all S 284319), beta: 0.00000000
day 6, H3N2: new I 0 (all I 0, all S 274191), beta: nan
day 6, B: new I 0 (all I 0, all S 222317), beta: nan

Proc MainProcess, Day 6, time elapsed: 0.40118619999975635 sec
All inf:  4674
day 7, H1N1: new I 0 (all I 4674, all S 284319), beta: 0.00000000
day 7, H3N2: new I 0 (all I 0, all S 274179), beta: nan
day 7, B: new I 0 (all I 0, all S 222307), beta: nan

Proc MainProcess, Day 7, time elapsed: 0.4133427000001575 sec
All inf:  4674
day 8, H1N1: new I 0 (all I 4674, all S 284319), beta: 0.00000000
day 8, H3N2: new I 0 (all I 0, all S 274179), beta: nan
day 8, B: new I 0 (all I 0, all S 222307), beta: nan

Proc MainProcess, Day 8, time elapsed: 0.4103944000003139 sec
All inf:  3369
day 9, H1N1: new I 0 (all I 3369, all S 284319), beta: 0.00000000
day 9, H3N2: new I 0 (all I 0, all S 273219), beta: nan
day 9, B: new I 0 (all I 0, all S 221518), beta: nan

Proc MainProcess, Day 9, time elapsed: 0.34512750000021697 sec

In [31]:
SEIRb_day

,S_H1N1,E_H1N1,I_H1N1,R_H1N1,beta_H1N1,S_H3N2,E_H3N2,I_H3N2,R_H3N2,beta_H3N2,S_B,E_B,I_B,R_B,beta_B
1,287688.0,1305.0,20.0,81516.0,0.000003,274191.0,0.0,0.0,95985.0,0.0,222317.0,0.0,0.0,147686.0,0.0
2,286968.0,2025.0,20.0,81516.0,0.000000,274191.0,0.0,0.0,95798.0,0.0,222317.0,0.0,0.0,147405.0,0.0
3,284319.0,3369.0,1325.0,81516.0,0.000003,274191.0,0.0,0.0,95129.0,0.0,222317.0,0.0,0.0,146355.0,0.0
4,284319.0,2649.0,2045.0,81516.0,0.000001,274191.0,0.0,0.0,95129.0,0.0,222317.0,0.0,0.0,146355.0,0.0
5,284319.0,0.0,4694.0,81516.0,0.000002,274191.0,0.0,0.0,95129.0,0.0,222317.0,0.0,0.0,146355.0,0.0
6,284319.0,0.0,4694.0,81516.0,0.000000,274191.0,0.0,0.0,95129.0,0.0,222317.0,0.0,0.0,146355.0,0.0
7,284319.0,0.0,4674.0,81536.0,0.000000,274179.0,0.0,0.0,95149.0,0.0,222307.0,0.0,0.0,146375.0,0.0
8,284319.0,0.0,4674.0,81536.0,0.000000,274179.0,0.0,0.0,95149.0,0.0,222307.0,0.0,0.0,146375.0,0.0
9,284319.0,0.0,3369.0,82841.0,0.000000,273219.0,0.0,0.0,96454.0,0.0,221518.0,0.0,0.0,147680.0,0.0